export default [
    { id:1, name:"烤肉拌饭", image_url:"shops_1" },
    { id:2, name:"贡菜", image_url:"shops_2" },
    { id:3, name:"吉野家", image_url:"shops_3" },
    { id:4, name:"麦当劳", image_url:"shops_4" },
    { id:5, name:"田老师", image_url:"shops_5" },
    { id:6, name:"南城香", image_url:"shops_6" },
    { id:7, name:"烤肉拌饭", image_url:"shops_1" },
    { id:8, name:"贡菜", image_url:"shops_2" },
    { id:9, name:"吉野家", image_url:"shops_3" },
    { id:10, name:"麦当劳", image_url:"shops_4" },
    { id:11, name:"田老师", image_url:"shops_5" },
    { id:12, name:"南城香", image_url:"shops_6" },
    { id:13, name:"烤肉拌饭", image_url:"shops_1" },
    { id:14, name:"贡菜", image_url:"shops_2" },
    { id:15, name:"吉野家", image_url:"shops_3" },
    { id:16, name:"麦当劳", image_url:"shops_4" },
    { id:17, name:"田老师", image_url:"shops_5" },
    { id:18, name:"南城香", image_url:"shops_6" },
]