export default{
    chicken: require('./chicken.jpg'),
    mdl: require('./mdl.jpg'),
    ricenoodle: require('./ricenoodle.jpg'),
    coffee: require('./coffee.jpg'),

    category_bao: require('./category_bao.png'),
    category_chuan: require('./category_bao.png'),
    category_guo: require('./category_guo.png'),
    category_han: require('./category_han.png'),
    category_jian: require('./category_jian.png'),
    category_ma: require('./category_ma.png'),
    category_mei: require('./category_mei.png'),
    category_pi: require('./category_pi.png'),
    category_ri: require('./category_ri.png'),
    category_shang: require('./category_shang.png'),
    category_tian: require('./category_tian.png'),
    category_tu: require('./category_tu.png'),
    category_xian: require('./category_xian.png'),
    category_xin: require('./category_xin.png'),
    category_yu: require('./category_yu.png'),
    category_zhun: require('./category_zhun.png'),

    shops_1: require('./shops_1.png'),
    shops_2: require('./shops_2.png'),
    shops_3: require('./shops_3.png'),
    shops_4: require('./shops_4.png'),
    shops_5: require('./shops_5.png'),
    shops_6: require('./shops_6.png'),

}